Pull request
PopovIV/intelligent-placer pull request #1
Opened 2022-09-16 18:00 UTC by PopovIV

2022-10-12 19:30 UTC, A21l63 reviewed
Ревью от Лаэтина Андрея

2022-10-12 19:30 UTC, A21l63 commented on README.md
> ++ Рассматриваются только предметы из предварительно подготовленного набора
Насколько я помню, говорилось, что предметы могут быть произвольными, главное, чтобы они удовлетворяли поставленным требованиям

2022-10-12 19:30 UTC, A21l63 commented on README.md
> ++ Нет повторяющихся предметов на фотографии
А почему нельзя сфотографировать два одинаковых предмета? Они, скорее всего, не могут быть полностью идентичными.  Не является ли это требование излишне строгим?

2022-10-12 19:30 UTC, A21l63 commented on README.md
> ++ Нарисован черным маркером/фломасетром на белом листе бумаги; На формат листа бумаги ограничений нет
Следует ли из этого, что линия должна иметь какую-либо минимальную толщину в пикселях?

2022-10-12 19:30 UTC, A21l63 commented on README.md
> ++ Однотонная горизонтальная поверхность белого цвета
Не будет ли она сливаться с границами листа?

2022-10-12 19:30 UTC, A21l63 commented on README.md
> +
Не стоит ли добавить требование отсутствия бликов?

2022-10-12 19:30 UTC, A21l63 commented on README.md
> +    2.1. Для маски многоугольника должен преобладать белый цвет.<br/>
Рассмотрены ли случаи, когда предмет **лежит внутри многоугольника** или на фотографии имеется прямоугольный объект белого цвета, имеющий размеры и пропорции, сопоставимые с размерами листа, что **удовлетворяет** Вашим **требованиям**?

2022-10-12 19:30 UTC, A21l63 commented on README.md
> +2. Далее, начиная с самого большого по площади объекта, будем пытаться найти приемлемое расположение для всех объектов:<br/>
Есть ли ограничения на время работы программы (перебор может оказаться слишком долгим)?

2022-10-12 19:30 UTC, A21l63 commented on test_cases/true/README.md
> +
В требованиях не написано, может ли объект пересекать границу листа. Правильно ли я понял, что такой случай допустим?

2022-10-13 10:46 UTC, Sairsey requested changes

2022-10-13 10:46 UTC, Sairsey commented on README.md
> +    2.2. Все остальные компоненты связности с достаточно большой площадью можно считать масками предметов.<br/>
Стоит сказать что-нибудь про тени от объектов. Они присутствуют на примерах, но ни слова о них нет в описании задачи

2022-10-13 20:09 UTC, PopovIV commented on README.md
> ++ Рассматриваются только предметы из предварительно подготовленного набора
Если обращаться к примеру и постановке задачи из файла(https://docs.google.com/document/d/1o0lawEvLgmh9VrA5fUlOHFvo5JKxR4NThCFobmrKz60/edit#), то я это интерпретировал так.

2022-10-13 20:17 UTC, PopovIV commented on README.md
> ++ Нет повторяющихся предметов на фотографии
Вообще не сложно сфотографировать два одинаковых предмета, хотя из моего набора предметов дубликаты есть далеко не у всех. Скорее это небольшое упрощение работы для меня, потому что не придется дополнительно хранить количество конкретных предметов на фотографии, поэтому мне это требование не кажется строгим.

2022-10-13 20:32 UTC, PopovIV commented on README.md
> ++ Нарисован черным маркером/фломасетром на белом листе бумаги; На формат листа бумаги ограничений нет
Добавлю требование на то, чтобы толщина была не менее 1мм. Зачем задавать значение в пикселях, это кажется логичным при проверке или создании изображения на компьютере, но если тесты будет готовить человек руками, то это требование его смутит.

2022-10-13 20:46 UTC, PopovIV commented on README.md
> ++ Однотонная горизонтальная поверхность белого цвета
На моих тестовых примерах проблем с этим нет. Но тут больше вопрос к освещению, а не поверхности тогда. При желании можно было бы сделать так, чтобы границы сливались. Добавлю отдельный пункт про освещение.

2022-10-13 20:46 UTC, PopovIV commented on README.md
> +
Это войдет в пункт про освещение

2022-10-13 20:49 UTC, PopovIV commented on README.md
> +    2.1. Для маски многоугольника должен преобладать белый цвет.<br/>
Предмет не может лежать внутри многоугольника. Думаю, что на этом этапе это можно проверять будет. Белых предметов в моем наборе нет, на этом и строится данных шаг алгоритма.

2022-10-13 20:52 UTC, PopovIV commented on test_cases/true/README.md
> +
Да, это усложнение задачи по идее. Допишу, что предмет не только может находиться на листе бумаги, но и пересекать его, это подразумевалось.

2022-10-13 20:54 UTC, PopovIV commented on README.md
> +2. Далее, начиная с самого большого по площади объекта, будем пытаться найти приемлемое расположение для всех объектов:<br/>
Вообще хотелось бы получать ответ за разумное время, но сейчас сложно давать какие-то точные оценки. Сейчас могу только поставить ограничение на время работы программы, но не максимальное время работы алгоритма.

2022-10-13 21:09 UTC, PopovIV commented on README.md
> +    2.2. Все остальные компоненты связности с достаточно большой площадью можно считать масками предметов.<br/>
Я добавлю про это в пункт, связанный с освещением. Скорее всего, избавиться от теней при данном освещении не получится. Поэтому сейчас просто напишу, что они будут считаться продолжением предмета, при этом тени не будут пересекать другие тени/предметы. Может смогу уже на уровне программы что-то с ними сделать, но ничего обещать не могу.

2022-10-28 01:07 UTC, merged